version: "3.3"

services:
  prom-database:
    image: mongo
    container_name: prom-database-container
    ports:
      - "27017:27017"
  prom-service:
    image: thannersoares/prom-service-image
    container_name: prom-service-container
    build: .
    ports:
      - "5000:5000"
    links:
      - prom-database
    depends_on:
      - prom-database

