version: "3.9"

services:
#  prom-database:
  #    image: mongo
  #    container_name: prom-database-container
  #    ports:
  #      - "27017:27017"
  prom-service:
    image: prom-service-image
    container_name: prom-service-container
    build: .
    ports:
      - "5000:5000"
#    depends_on:
#      - prom-database

